"""app_profile_ingestion_enabled

Revision ID: 04441d5bcea8
Revises: 80a52cdcc2eb
Create Date: 2026-05-16 18:58:58.754430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04441d5bcea8'
down_revision: Union[str, None] = '80a52cdcc2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_profiles', sa.Column('ingestion_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_profiles', 'ingestion_enabled')
    # ### end Alembic commands ###
