"""add_ambiguity_score_to_classification

Revision ID: 29f9f9fdc8f1
Revises: bb06ee99b747
Create Date: 2026-04-21 23:53:29.429416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f9f9fdc8f1'
down_revision: Union[str, None] = 'bb06ee99b747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_results', sa.Column('ambiguity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_results', 'ambiguity_score')
    # ### end Alembic commands ###
