"""phase2_intelligence_models

Revision ID: 80a52cdcc2eb
Revises: 29f9f9fdc8f1
Create Date: 2026-05-16 18:20:45.116492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a52cdcc2eb'
down_revision: Union[str, None] = '29f9f9fdc8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.Enum('FINANCE', 'FINTECH', 'COMMERCE', 'DELIVERY', 'PUBLIC', 'EDUCATION', 'MOBILITY', 'ENTERTAINMENT', 'OTHER', name='company_industry', native_enum=False, length=32), nullable=False),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('app_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', 'BOTH', name='app_platform', native_enum=False, length=16), nullable=False),
    sa.Column('app_store_id', sa.String(length=128), nullable=True),
    sa.Column('play_store_package', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), server_default='kr', nullable=False),
    sa.Column('is_target', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_competitor', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_profiles_company_id'), 'app_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_app_profiles_id'), 'app_profiles', ['id'], unique=False)
    op.create_table('app_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_app_id', sa.UUID(), nullable=False),
    sa.Column('competitor_app_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('comparison_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_app_id'], ['app_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_benchmarks_id'), 'app_benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_app_benchmarks_target_app_id'), 'app_benchmarks', ['target_app_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.Enum('RISK', 'OPPORTUNITY', 'COMPETITIVE_GAP', 'UX_PROBLEM', 'TECHNICAL_ISSUE', 'OPERATION_ISSUE', 'CUSTOMER_SUPPORT_ISSUE', name='insight_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_review_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='insight_severity_enum', native_enum=False, length=16), nullable=False),
    sa.Column('business_impact', sa.Enum('RETENTION', 'CONVERSION', 'TRUST', 'BRAND', 'COST', 'COMPLIANCE', 'UNKNOWN', name='insight_business_impact_enum', native_enum=False, length=32), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_app_id'), 'insights', ['app_id'], unique=False)
    op.create_index(op.f('ix_insights_company_id'), 'insights', ['company_id'], unique=False)
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('COMPANY_APP_REVIEW', 'COMPETITIVE_BENCHMARK', 'MONTHLY_VOC', 'SALES_OUTBOUND', name='report_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('period_start', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.String(length=16), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'EXPORTED', 'SENT', name='report_status_enum', native_enum=False, length=16), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_app_id'), 'reports', ['app_id'], unique=False)
    op.create_index(op.f('ix_reports_company_id'), 'reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('review_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.Enum('UX', 'BUG', 'PERFORMANCE', 'POLICY', 'OPERATION', 'CUSTOMER_SUPPORT', 'PRICING', 'SECURITY', 'AUTHENTICATION', 'UNKNOWN', name='cluster_issue_type', native_enum=False, length=32), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='cluster_severity', native_enum=False, length=16), nullable=False),
    sa.Column('representative_review_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['app_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_clusters_app_id'), 'review_clusters', ['app_id'], unique=False)
    op.create_index(op.f('ix_review_clusters_id'), 'review_clusters', ['id'], unique=False)
    op.add_column('reviews', sa.Column('app_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reviews_app_id'), 'reviews', ['app_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'app_profiles', ['app_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_app_id'), table_name='reviews')
    op.drop_column('reviews', 'app_id')
    op.drop_index(op.f('ix_review_clusters_id'), table_name='review_clusters')
    op.drop_index(op.f('ix_review_clusters_app_id'), table_name='review_clusters')
    op.drop_table('review_clusters')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_company_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_app_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_company_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_app_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_app_benchmarks_target_app_id'), table_name='app_benchmarks')
    op.drop_index(op.f('ix_app_benchmarks_id'), table_name='app_benchmarks')
    op.drop_table('app_benchmarks')
    op.drop_index(op.f('ix_app_profiles_id'), table_name='app_profiles')
    op.drop_index(op.f('ix_app_profiles_company_id'), table_name='app_profiles')
    op.drop_table('app_profiles')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
